# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7566f6fc7dc764d5d1f62af64ef7ce3e812746609189664f0382a05cb17450485c339d99a2e41e7270f8381469fa5b064475e91f282fba0aa8867a65089fc1f

test:
  secret_key_base: a63da487dea7064890a1bd29624611ed8ef1636754aa55d1c68834d9eb310b0c7a9e64c7bad5ab97ad586b7508f7abc7a929b4b61cb329a5a29fb61c9243919e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
